### ISSUE TITLE
Research nice materials for the laser cutter

### ISSUE THREAD

**Issue by vogelino** [FH-Potsdam/bit-nickel-weasel#1]
From asana from @wollemannone :
http://www.modulor.de/edelstahlkugel-glaenzend-hohl.html
http://www.modulor.de/polystyrol-spiegel-farbig-glatt.html
http://www.modulor.de/korkkugel-ungebohrt.html
https://www.pololu.com/
http://www.modulor.de/naturkork-platten-ungeschliffen.html
http://www.modulor.de/kupferblech-tafeln.html
http://www.kraftplex.com/kraftplex/

**Comment by wollemannone** [comment]
Also ich habe von dem Kraftplex mal ne Paterialprobe angefordert. Ich deke für MAterialrecherche reicht es an diesem Punkt. Es macht erst Sinn weiter über das Moterial zu sprechen, wenn wir ein Konzept haben bzw. wissen was das Material können soll
