### ISSUE TITLE
Split Team responsabilities

### ISSUE THREAD

**Issue by vogelino** [FH-Potsdam/bit-nickel-weasel#3]
Form asana by @vogelino:
- @vogelino: Development (approved) 
- @wollemannone: Product conception (pending approbation)
- @dariaDunkelbier: Organisation and communication (approved)

**Comment by vogelino** [comment]
@FH-Potsdam/connecting-bits-nickel-weasel Is it okay for you?

**Comment by vogelino** [comment]
@wollemannone: Ping!

**Comment by wollemannone** [comment]
what does that mean? I need to confirm my tasks right?

**Comment by vogelino** [comment]
Right! Are you ok with the idea of being responsible for the physical product conception? Close the issue if so. Thx!

**Comment by wollemannone** [comment]
Yes I am :)
