### ISSUE TITLE
Obtain two photon boards

### ISSUE THREAD

**Issue by vogelino** [FH-Potsdam/bit-nickel-weasel#4]
@dariaDunkelbier und @wollemannone.  Ich habe eine Seite gefunden wo man photos für 19$ kaufen kann. Ich würde eine für mich bestellen. Hätte eins von euch bock auf eins? Dann hätten wir zwei. https://store.particle.io/

**Comment by vogelino** [comment]
Edit: Es würde mit Versand (21.20$) 42$ kosten, wenn man eins bestellt und 62$ (31$/Stück) wenn man gleich zwei bestellt. Sagt bescheid.

**Comment by vogelino** [comment]
Auf amazon habe ich photon boards für 28,55€ inkl. Versand gefunden. Da es aber kein grosses unterschied mit das original Verkäufer macht, würde ich lieber direkt bei Particle bestellen. Eventuell könnten wir gucken ob wir uns der Preis des Versands noch verringern könnte wenn man mehr mit andere Studenten auf einmal bestellen würde. Ich poste mal was auf Incom.

**Comment by vogelino** [comment]
@FH-Potsdam/steel-ant-io What do you think? Does someone still need to get some photon boards? Let me know. I can order them from my account. If I do it soon we could have them for the beginning of January.

**Comment by fabiantheblind** [comment]
@vogelino I think it will take some time to order from the US. Also it will get stuck in the customs (Zoll) so somebody will habe to pick it up and pay the import fees. thats 19% so you wont really save money. Thats why I suggested to buy them at exp-tech.de. I also have some Photonboards in the lab. So if you are so eager to buy them in the US you can get one from me and later when yours arrive we can exchange them.

**Comment by fabiantheblind** [comment]
@vogelino and @FH-Potsdam/steel-ant-io This is a good bargain http://www.exp-tech.de/photon-kit 
You'll get a Micro-USB cable and breadboard with some sensor.

**Comment by vogelino** [comment]
https://fhp.incom.org/post/163868

**Comment by vogelino** [comment]
We even get three! :)

**Comment by vogelino** [comment]
@FH-Potsdam/connecting-bits-nickel-weasel I've got our three photon boards! Nice! Please let me know when you transferred the money to my account! Peace! (Look at the email of your incom account)
![img_0938](https://cloud.githubusercontent.com/assets/2759340/12208428/ee83567a-b64c-11e5-9cf5-bf67ac1af599.JPG)
